/* Bilgi Kupası soruları. Her sorunun ilk seçeneği doğru cevaptır, oyun seçenekleri karıştırarak gösterir.
   kucuk: 5 yaş, resimli ve sesli okunur. o: [emoji, ad]
   orta: 8-10 yaş. buyuk: 12 yaş ve üstü. e: cevaptan sonra gösterilen kısa bilgi */
window.BILGI_SORULAR = {
  kucuk: [
    {q:"Hangisi uçar?", o:[["🐦","kuş"],["🐟","balık"],["🐢","kaplumbağa"]]},
    {q:"Hangisi suda yaşar?", o:[["🐟","balık"],["🐈","kedi"],["🐄","inek"]]},
    {q:"Hangisi bir meyve?", o:[["🍎","elma"],["🥕","havuç"],["🧀","peynir"]]},
    {q:"Hangisi bir sebze?", o:[["🥕","havuç"],["🍇","üzüm"],["🍰","pasta"]]},
    {q:"Hangisi sarı?", o:[["🍌","muz"],["🍓","çilek"],["🥦","brokoli"]]},
    {q:"Hangisi kırmızı?", o:[["🍓","çilek"],["🍌","muz"],["🥒","salatalık"]]},
    {q:"Havlayan hayvan hangisi?", o:[["🐶","köpek"],["🐱","kedi"],["🐑","koyun"]]},
    {q:"Miyavlayan hayvan hangisi?", o:[["🐱","kedi"],["🐶","köpek"],["🐴","at"]]},
    {q:"Bize süt veren hayvan hangisi?", o:[["🐄","inek"],["🐔","tavuk"],["🐸","kurbağa"]]},
    {q:"Yumurtlayan hayvan hangisi?", o:[["🐔","tavuk"],["🐄","inek"],["🐶","köpek"]]},
    {q:"Arı bize ne verir?", o:[["🍯","bal"],["🥛","süt"],["🥚","yumurta"]]},
    {q:"Gece gökyüzünde hangisini görürüz?", o:[["🌙","ay"],["🌈","gökkuşağı"],["🏖️","plaj"]]},
    {q:"Güneş hangisi?", o:[["☀️","güneş"],["🌙","ay"],["⭐","yıldız"]]},
    {q:"Yağmur yağarken ne kullanırız?", o:[["☂️","şemsiye"],["🕶️","güneş gözlüğü"],["🧤","eldiven"]]},
    {q:"Kışın soğukta hangisini takarız?", o:[["🧣","atkı"],["🩳","şort"],["👙","mayo"]]},
    {q:"Hangisi bir taşıt?", o:[["🚗","araba"],["🌳","ağaç"],["🏠","ev"]]},
    {q:"Hangisi raylarda gider?", o:[["🚂","tren"],["🚗","araba"],["🚲","bisiklet"]]},
    {q:"Hangisi gökyüzünde uçar?", o:[["✈️","uçak"],["🚌","otobüs"],["⛵","yelkenli"]]},
    {q:"Çorbayı ne ile içeriz?", o:[["🥄","kaşık"],["✂️","makas"],["🧦","çorap"]]},
    {q:"Hangisi en büyük hayvan?", o:[["🐘","fil"],["🐭","fare"],["🐰","tavşan"]]},
    {q:"Hangisi en küçük?", o:[["🐜","karınca"],["🐘","fil"],["🦒","zürafa"]]},
    {q:"Boynu en uzun hayvan hangisi?", o:[["🦒","zürafa"],["🐻","ayı"],["🐧","penguen"]]},
    {q:"Hangi hayvan zıplayarak gider?", o:[["🦘","kanguru"],["🐌","salyangoz"],["🐟","balık"]]},
    {q:"Hangisi sıcak?", o:[["🔥","ateş"],["🧊","buz"],["⛄","kardan adam"]]},
    {q:"Hangisi soğuk?", o:[["🧊","buz"],["🔥","ateş"],["☀️","güneş"]]},
    {q:"Hangisi üçgen?", o:[["🔺","üçgen"],["🔵","daire"],["🟥","kare"]]},
    {q:"Hangisi daire?", o:[["🔵","daire"],["🔺","üçgen"],["🟥","kare"]]},
    {q:"Hangisiyle resim yaparız?", o:[["🖍️","boya kalemi"],["🍽️","tabak"],["🧦","çorap"]]},
    {q:"Hangisi bir çiçek?", o:[["🌻","ayçiçeği"],["🍄","mantar"],["🥔","patates"]]},
    {q:"Kaç tane elma var?", img:"🍎🍎🍎", o:[["3",""],["2",""],["5",""]]},
    {q:"Kaç tane yıldız var?", img:"⭐⭐", o:[["2",""],["4",""],["1",""]]},
    {q:"Kaç tane balon var?", img:"🎈🎈🎈🎈", o:[["4",""],["3",""],["6",""]]},
    {q:"Kaç tane ördek var?", img:"🦆", o:[["1",""],["2",""],["3",""]]},
    {q:"Kaç tane araba var?", img:"🚗🚗🚗🚗🚗", o:[["5",""],["4",""],["6",""]]}
  ],
  orta: [
    {q:"Bir haftada kaç gün vardır?", o:["7","5","6","8"]},
    {q:"Bir yılda kaç ay vardır?", o:["12","10","11","13"]},
    {q:"Türkiye'nin başkenti neresidir?", o:["Ankara","İstanbul","İzmir","Bursa"]},
    {q:"Türkiye'nin en kalabalık şehri hangisidir?", o:["İstanbul","Ankara","Antalya","Konya"]},
    {q:"Su kaç derecede donar?", o:["0 °C","10 °C","100 °C","50 °C"], e:"Deniz seviyesinde saf su 0 °C'de donar, 100 °C'de kaynar."},
    {q:"Yaşadığımız gezegenin adı nedir?", o:["Dünya","Mars","Venüs","Jüpiter"]},
    {q:"Örümceklerin kaç bacağı vardır?", o:["8","6","4","10"], e:"Örümcekler böcek değildir, 8 bacaklı eklem bacaklılardır."},
    {q:"Böceklerin kaç bacağı vardır?", o:["6","8","4","10"]},
    {q:"Hangisi bir memelidir?", o:["Yunus","Köpekbalığı","Kartal","Timsah"], e:"Yunuslar denizde yaşar ama memelidir, yavrularını emzirir."},
    {q:"Arılar balı neyden yapar?", o:["Çiçek özünden","Yapraktan","Sudan","Topraktan"]},
    {q:"8 + 7 kaç eder?", o:["15","14","16","13"]},
    {q:"6 × 7 kaç eder?", o:["42","36","48","49"]},
    {q:"Bir saatte kaç dakika vardır?", o:["60","100","30","90"]},
    {q:"Yapraklar hangi mevsimde sararıp dökülür?", o:["Sonbahar","İlkbahar","Yaz","Kış"]},
    {q:"Dünyanın en büyük okyanusu hangisidir?", o:["Büyük Okyanus","Atlas Okyanusu","Hint Okyanusu","Arktik Okyanusu"], e:"Büyük Okyanus'a Pasifik Okyanusu da denir."},
    {q:"Bitkiler besin üretmek için neye ihtiyaç duyar?", o:["Güneş ışığına","Karanlığa","Plastiğe","Tuza"], e:"Bitkiler güneş ışığı, su ve havadaki karbondioksitle besin üretir. Buna fotosentez denir."},
    {q:"İstanbul'u ikiye ayıran boğazın adı nedir?", o:["İstanbul Boğazı","Çanakkale Boğazı","Cebelitarık Boğazı","Hürmüz Boğazı"]},
    {q:"Türk bayrağında hangi şekiller vardır?", o:["Ay ve yıldız","Güneş ve yıldız","İki yıldız","Ay ve güneş"]},
    {q:"Üç kenarı olan şekle ne denir?", o:["Üçgen","Kare","Daire","Beşgen"]},
    {q:"Hangisi bir gezegen değildir?", o:["Ay","Mars","Satürn","Merkür"], e:"Ay, Dünya'nın etrafında dönen bir uydudur."},
    {q:"Penguenler en çok nerede yaşar?", o:["Antarktika","Sahra Çölü","Amazon Ormanı","Himalayalar"]},
    {q:"Bir düzine kaç tanedir?", o:["12","10","6","20"]},
    {q:"Oda sıcaklığında hangisi sıvıdır?", o:["Su","Buz","Taş","Tahta"]},
    {q:"Ağaçlar havaya hangi gazı verir?", o:["Oksijen","Duman","Helyum","Buhar"], e:"Ağaçlar karbondioksiti alır, soluduğumuz oksijeni verir."},
    {q:"Kaplumbağalar nasıl dünyaya gelir?", o:["Yumurtadan çıkarak","Tohumdan filizlenerek","Kozadan çıkarak","Sudan doğarak"]},
    {q:"100'ün yarısı kaçtır?", o:["50","25","20","40"]},
    {q:"Hangi hayvan kış uykusuna yatar?", o:["Ayı","Köpek","Tavuk","At"]},
    {q:"Gündüz gökyüzünde gördüğümüz yıldız hangisidir?", o:["Güneş","Kutup Yıldızı","Ay","Mars"], e:"Güneş bize en yakın yıldızdır."},
    {q:"Bir asır kaç yıldır?", o:["100","10","50","1000"]},
    {q:"Hangi organımızla nefes alırız?", o:["Akciğer","Kalp","Böbrek","Kulak"]},
    {q:"Bir karenin kaç köşesi vardır?", o:["4","3","5","6"]}
  ],
  buyuk: [
    {q:"Güneş sistemindeki en büyük gezegen hangisidir?", o:["Jüpiter","Satürn","Dünya","Neptün"], e:"Jüpiter'in içine 1.300'den fazla Dünya sığabilir."},
    {q:"Suyun kimyasal formülü nedir?", o:["H₂O","CO₂","O₂","NaCl"], e:"İki hidrojen ve bir oksijen atomu. NaCl ise sofra tuzudur."},
    {q:"Türkiye Cumhuriyeti hangi yıl ilan edildi?", o:["1923","1919","1920","1938"], e:"Cumhuriyet 29 Ekim 1923'te ilan edildi."},
    {q:"Atatürk Samsun'a hangi tarihte çıktı?", o:["19 Mayıs 1919","23 Nisan 1920","30 Ağustos 1922","29 Ekim 1923"]},
    {q:"Türkiye Büyük Millet Meclisi hangi tarihte açıldı?", o:["23 Nisan 1920","19 Mayıs 1919","29 Ekim 1923","10 Kasım 1938"]},
    {q:"Türkiye'nin en yüksek dağı hangisidir?", o:["Ağrı Dağı","Erciyes Dağı","Uludağ","Palandöken"], e:"Ağrı Dağı yaklaşık 5.137 metre yüksekliğindedir."},
    {q:"Tamamı Türkiye sınırları içinde olan en uzun nehir hangisidir?", o:["Kızılırmak","Fırat","Dicle","Meriç"], e:"Kızılırmak yaklaşık 1.355 km'dir. Fırat daha uzundur ama Suriye ve Irak'tan da geçer."},
    {q:"Işık saniyede yaklaşık kaç kilometre yol alır?", o:["300.000 km","3.000 km","30.000 km","3 milyon km"], e:"Güneş'ten çıkan ışık Dünya'ya yaklaşık 8 dakikada ulaşır."},
    {q:"İnsan vücudundaki en büyük organ hangisidir?", o:["Deri","Karaciğer","Kalp","Beyin"]},
    {q:"Hangisi bir asal sayıdır?", o:["13","21","27","15"], e:"13 yalnızca 1'e ve kendisine bölünür. 21 = 3 × 7, 27 = 3 × 9, 15 = 3 × 5."},
    {q:"Bir üçgenin iç açılarının toplamı kaç derecedir?", o:["180","90","360","270"]},
    {q:"Hücrede kalıtım bilgisi (DNA) çoğunlukla nerede bulunur?", o:["Çekirdekte","Hücre zarında","Kofulda","Hücre duvarında"]},
    {q:"Mona Lisa tablosunu kim yapmıştır?", o:["Leonardo da Vinci","Pablo Picasso","Vincent van Gogh","Michelangelo"]},
    {q:"Ay'a ayak basan ilk insan kimdir?", o:["Neil Armstrong","Yuri Gagarin","Buzz Aldrin","Alper Gezeravcı"], e:"1969'da Apollo 11 göreviyle. Alper Gezeravcı 2024'te uzaya giden ilk Türk astronottur."},
    {q:"Uzaya çıkan ilk insan kimdir?", o:["Yuri Gagarin","Neil Armstrong","Valentina Tereşkova","Alper Gezeravcı"], e:"Yuri Gagarin 1961'de uzaya çıktı. Tereşkova ise uzaya çıkan ilk kadındır."},
    {q:"Hangisi yenilenebilir bir enerji kaynağıdır?", o:["Rüzgâr","Kömür","Doğalgaz","Petrol"]},
    {q:"Bir bayt kaç bitten oluşur?", o:["8","2","10","16"]},
    {q:"İstanbul hangi iki kıtayı birbirine bağlar?", o:["Avrupa ve Asya","Asya ve Afrika","Avrupa ve Afrika","Asya ve Amerika"]},
    {q:"Yunuslar nefes almak için hangi organı kullanır?", o:["Akciğer","Solungaç","Deri","Yüzgeç"], e:"Yunuslar memelidir, nefes almak için su yüzeyine çıkarlar."},
    {q:"81'in karekökü kaçtır?", o:["9","8","7","27"]},
    {q:"Pi sayısının yaklaşık değeri hangisidir?", o:["3,14","2,71","1,61","4,13"]},
    {q:"Hangisi bir programlama dilidir?", o:["Python","Photoshop","Excel","Chrome"]},
    {q:"Ses hangi ortamda yayılamaz?", o:["Boşlukta","Suda","Havada","Demirde"], e:"Sesin yayılması için madde gerekir, bu yüzden uzay boşluğunda ses duyulmaz."},
    {q:"Mars neden kırmızımsı görünür?", o:["Toprağındaki demir oksit yüzünden","Yüzeyindeki lav gölleri yüzünden","Kırmızı bitkiler yüzünden","Güneş'e çok yakın olduğu için"], e:"Demir oksit, bildiğimiz pasın ta kendisidir."},
    {q:"Hangisi bir satranç taşı değildir?", o:["Asker","Vezir","Fil","Kale"], e:"Satrançtaki en küçük taşın adı piyondur."},
    {q:"Olimpiyat bayrağında kaç halka vardır?", o:["5","4","6","7"]},
    {q:"Dünya kendi etrafında bir turu yaklaşık ne kadar sürede döner?", o:["24 saat","365 gün","30 gün","12 saat"], e:"Güneş'in etrafındaki bir turu ise yaklaşık 365 gün sürer."},
    {q:"Halkalarıyla ünlü gezegen hangisidir?", o:["Satürn","Mars","Merkür","Venüs"]},
    {q:"Yetişkin bir insanın vücudunda kaç kemik vardır?", o:["206","106","306","156"]},
    {q:"Everest Dağı hangi sıradağlarda yer alır?", o:["Himalayalar","Alpler","And Dağları","Toros Dağları"]},
    {q:"Bir sayının yüzde 50'si neye eşittir?", o:["Yarısına","Çeyreğine","İki katına","Kendisine"]},
    {q:"Hangisi bir yazılım değil, bir donanımdır?", o:["Klavye","Web tarayıcısı","İşletim sistemi","Oyun uygulaması"]}
  ]
};
